---
- name: Setup vagrant with libvirt provider
  hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: Install vagrant
      yum:
        name: https://releases.hashicorp.com/vagrant/2.1.4/vagrant_2.1.4_x86_64.rpm
        state: present

    - name: Install libvirt plugin supporting package
      yum:
        name:
          - qemu
          - libvirt
          - libvirt-devel
          - ruby-devel
          - gcc
          - qemu-kvm
    - name: set up proxy server
      shell: export https_proxy=http://192.168.1.3:808

    - name: install libvirt plugin
      shell: vagrant plugin install vagrant-libvirt


