---
- name: set a specific dns server
  hosts: all
  become: yes

  tasks:
    - name: set dns server
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 192.168.1.200'

    - name: set dns server
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth1
        regexp: '^PEERDNS='
        line: 'PEERDNS=yes'

    - name: set dns server
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: '^PEERDNS='
        line: 'PEERDNS=no'
