Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus =2 
      domain.storage :file, :size => '20G'
    end
    master.vm.network :private_network, :ip => "172.25.250.11"
    master.vm.hostname = "master.fcg.io"
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end
    master.vm.synced_folder ".", "/vagrant", type: "nfs"

  end
end
