---
- name: install all-in-one openstack with packstack
  hosts: localhost
  become: yes
  vars:
    - version: queens

  tasks:
    - name: stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: stop and disable NetworkManager
      service:
        name: NetworkManager
        state: stopped
        enabled: no

    - name: disable Selinux
      selinux:
        policy: targeted
        state: permissive

    - name: Install epel
      yum:
        name:
          - epel-release.noarch
        state: present
        update_cache: yes
    - name: Install centos-release-openstack
      yum:
        name:
          - centos-release-openstack-{{ version }}
        state: present
        update_cache: yes


    - name: Install packstack
      yum:
        name:
          - openstack-packstack
          - openstack-utils
          - python-openstackclient
        state: present
        update_cache: yes


