---
- name: Provision softwore installation
  hosts: all
  become: yes
  become_user: root
  vars:
    softwares:
      - git
      - net-tools

  tasks:
    - name: Install {{ softwares }}
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ softwares }}"
